checks:
  php:
    code_rating: true
    duplication: true
    variable_existence: true
    useless_calls: true
    return_doc_comments: true
    parameter_doc_comments: true
    assignment_of_null_return: true
    no_trailing_whitespace: true
    one_class_per_file: true
    no_short_open_tag: true
    no_debug_code: true

tools:
  external_code_coverage:
    timeout: 600

build:
  environment:
    php:
      version: '8.2'

  dependencies:
    before:
      - composer install --no-interaction

  tests:
    override:
      -
        command: |
          vendor/bin/phpunit --coverage-clover=coverage.xml
        coverage:
          file: coverage.xml
          format: clover

filter:
  excluded_paths:
    - tests/*
    - vendor/*

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
    braces:
      classes_functions:
        class: new-line
        function: end-of-line
    spaces:
      around_operators:
        concatenation: true
