build:
  nodes:
    analysis:
      tests:
        override: []    # No ejecutar tests ni php-scrutinizer-run

filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
